behaviors:
  SphereAgentBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 6.0e-5
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
#      gail:
#        strength: 0.5
#        demo_path: Demos/RollerAgentDemo.demo
    max_steps: 5.0e6
    time_horizon: 200
    summary_freq: 20000